### ISSUE TITLE
folders inside cntrlr are empty

### ISSUE THREAD

**Issue by Diamondrubix** [Drakador/Hackathons#1]
why, what happend and why can't I find the original code. Who made the original repository?

**Comment by jehammer** [comment]
Seems like a github issue. Repo has not been touched in a while and I am not aware if I have any of the code on my Drives. I will take a look.

**Comment by jehammer** [comment]
I am unable to find the original code at this point in time. I will be removing the Project from Hackathons as a result until further notice.

**Comment by jehammer** [comment]
Final update: Size was too large due to overlooked OLDNOTSERVER and some hidden .git files that were not removed, leading to commit issues. Everything has since been corrected by reducing size via removal of OLDNOTSERVER and removal of the .git files inside the individual folders. 

Should be no further issues.
